name: Generate Snake

on:
  schedule: # Executa todo dia √†s 23:59
    - cron: "59 23 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do reposit√≥rio
        uses: actions/checkout@v3

      - name: Gerar a anima√ß√£o da cobrinha üêç
        uses: Platane/snk@v3
        with:
          github_user_name: Beatrizslb
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Enviar arquivo gerado
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
